### PR TITLE
Added Modman installation file

### PR DESCRIPTION
**Pull request by amacgregor**
Added modman file for easy installation and deployment.

### CODE REVIEW

**Comment by jreinke** [comment]
Sorry I don't want modman files to be added on my repositories.

**Comment by amacgregor** [comment]
Any particular reason you are against modman ?

**Comment by jreinke** [comment]
Nothing against modman since modgit source code is totally inspired from it.
I just don't like the files mapping concept but thanks for the proposal ;)

**Comment by amacgregor** [comment]
Awesome and completely understandable, personally modman has been really 
handy for setting up local testing environments, although we are still 
discussing the possibility of using as part of our production deployment 
workflow.

Also I'm doing a post about magento-mink http://www.demacmedia.com/blog/ 
it has been very useful as part of our development workflow.

Johann Reinke wrote:

**Comment by jreinke** [comment]
Again, I really don't have any problem with modman and the guys using it.
I just don't like mapping and symbolic links use, that's why modgit has been created.

By the way, I'm glad to see that magento-mink has been useful for your project.

**Comment by amacgregor** [comment]
Yup currently experimenting with a combination of magento-mink and 
MageTest for doing all our tests, I'll let you know how that goes. And 
I'll might give modgit a try.

Johann Reinke wrote:

**Comment by tronza** [comment]
Why not add composer.json or add in packagist as it has been a de-facto way of installing dependencies for years?

**Pull request closed without merging**
